#pragma once

constexpr unsigned short CtoGS_MSGAcknowledgeTrade = 0x0;
constexpr unsigned short CtoGS_MSGCancelTrade = 0x1;
constexpr unsigned short CtoGS_MSGAddItemTrade = 0x2;
constexpr unsigned short CtoGS_MSGSubmitOffer = 0x3;
constexpr unsigned short CtoGS_MSGRemoveItemTrade = 0x5;
constexpr unsigned short CtoGS_MSGChangeOffer = 0x6;
constexpr unsigned short CtoGS_MSGAcceptTrade = 0x7;
constexpr unsigned short CtoGS_MSGDisconnect = 0x9;
constexpr unsigned short CtoGS_MSGSetAttributes = 0x11; // + 1
constexpr unsigned short CtoGS_MSGAbandonQuest = 0x12; // ok
constexpr unsigned short CtoGS_MSGActivateQuest = 0x13; // ok
constexpr unsigned short CtoGS_MSGRequestQuest = 0x16; // ok
constexpr unsigned short CtoGS_MSGSetHeroAggression = 0x17;
constexpr unsigned short CtoGS_MSGLockHeroTarget = 0x18;
constexpr unsigned short CtoGS_MSGChangeHeroSkillSlotState = 0x1B; // -1
constexpr unsigned short CtoGS_MSGCommandHero = 0x1D;
constexpr unsigned short CtoGS_MSGCommandAll = 0x1E;
constexpr unsigned short CtoGS_MSGAddHero = 0x21; // -1
constexpr unsigned short CtoGS_MSGKickHero = 0x22; // -2
constexpr unsigned short CtoGS_MSGCallTarget = 0x28;
constexpr unsigned short CtoGS_MSGPingWeaponSet = 0x2C; // +1
constexpr unsigned short CtoGS_MSGCallSkill = 0x2D;
constexpr unsigned short CtoGS_MSGAttack = 0x2E;
constexpr unsigned short CtoGS_MSGCancelAction = 0x2F;
constexpr unsigned short CtoGS_MSGDropBuff = 0x30;
constexpr unsigned short CtoGS_MSGDrawMap = 0x32;
constexpr unsigned short CtoGS_MSGDropItem = 0x33;
constexpr unsigned short CtoGS_MSGDropGold = 0x36;
constexpr unsigned short CtoGS_MSGEquipItem = 0x37;
constexpr unsigned short CtoGS_MSGGoPlayer = 0x3A;
constexpr unsigned short CtoGS_MSGDonateFaction = 0x3C;
constexpr unsigned short CtoGS_MSGGoNPC = 0x40;
constexpr unsigned short CtoGS_MSGDialog = 0x42;
constexpr unsigned short CtoGS_MSGMouseMove = 0x45; // +1
constexpr unsigned short CtoGS_MSGPickUpItem = 0x46;
constexpr unsigned short CtoGS_MSGChangeSecondary = 0x48;
constexpr unsigned short CtoGS_MSGUseSkill = 0x4D;
constexpr unsigned short CtoGS_MSGStartTrade = 0x50;
constexpr unsigned short CtoGS_MSGTransactTrade = 0x51;
constexpr unsigned short CtoGS_MSGRequestQuote = 0x53;
constexpr unsigned short CtoGS_MSGTransactItem = 0x54;
constexpr unsigned short CtoGS_MSGGoGadget = 0x58;
constexpr unsigned short CtoGS_MSGOpenChest = 0x5A;
constexpr unsigned short CtoGS_MSGSetDisplayedTitle = 0x5F;
constexpr unsigned short CtoGS_MSGRemoveDisplayedTitle = 0x60;
constexpr unsigned short CtoGS_MSGSetSkillbarSkill = 0x63;
constexpr unsigned short CtoGS_MSGLoadSkillbar = 0x64; // TODO
constexpr unsigned short CtoGS_MSGSkipCinematic = 0x6A;
constexpr unsigned short CtoGS_MSGSendChat = 0x6B; // done
constexpr unsigned short CtoGS_MSGDeleteItem = 0x6F;
constexpr unsigned short CtoGS_MSGUnlockSkillByTome = 0x73;
constexpr unsigned short CtoGS_MSGIdentifyItem = 0x74;
constexpr unsigned short CtoGS_MSGMoveItem = 0x79; // done
constexpr unsigned short CtoGS_MSGAcceptAllItems = 0x7A; // Untested
constexpr unsigned short CtoGS_MSGSplitStack = 0x7C;
constexpr unsigned short CtoGS_MSGStartSalvage = 0x7E;
constexpr unsigned short CtoGS_MSGCancelSalvage = 0x7F;
constexpr unsigned short CtoGS_MSGEndSalvage = 0x80;
constexpr unsigned short CtoGS_MSGSalvageMaterials = 0x81;
constexpr unsigned short CtoGS_MSGSalvageMod = 0x82;
constexpr unsigned short CtoGS_MSGChangeGold = 0x83;
constexpr unsigned short CtoGS_MSGUseItem = 0x85;
constexpr unsigned short CtoGS_MSGRequestSpawn = 0x8E;
constexpr unsigned short CtoGS_MSGRequestAgents = 0x97;
constexpr unsigned short CtoGS_MSGRequestItems = 0x98;
constexpr unsigned short CtoGS_MSGSwitchMode = 0xA3;
constexpr unsigned short CtoGS_MSGAcceptPartyRequest = 0xA4;
constexpr unsigned short CtoGS_MSGCancelPartyRequest = 0xA5;
constexpr unsigned short CtoGS_MSGDenyPartyRequest = 0xA6;
constexpr unsigned short CtoGS_MSGAddNpc = 0xA7;
constexpr unsigned short CtoGS_MSGInvitePlayer = 0xA8;
constexpr unsigned short CtoGS_MSGLeaveParty = 0xAA;
constexpr unsigned short CtoGS_MSGEnterChallenge = 0xAC;
constexpr unsigned short CtoGS_MSGReturnToOutpost = 0xAF;
constexpr unsigned short CtoGS_MSGKickNpc = 0xB0;
constexpr unsigned short CtoGS_MSGKickPlayer = 0xB1;
constexpr unsigned short CtoGS_MSGTick = 0xB7;
constexpr unsigned short CtoGS_MSGTravelGH = 0xB8;
constexpr unsigned short CtoGS_MSGTravelTo = 0xB9; // ok
constexpr unsigned short CtoGS_MSGLeaveGH = 0xBA;